# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

script: skip

deploy:
  provider: pypi
  user: __token__
  password: $PYPI_KEY
  skip_cleanup: true
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: master